### ISSUE TITLE
See if keybindings work for the PBA pointer, setup for reveal.js use.

### ISSUE THREAD

**Issue by nuke-web3** [Polkadot-Blockchain-Academy/udev-norwii#1]
Norwii N95 Presentation Remote: https://smile.amazon.com/KNORVAY-Presentation-Highlighting-Rechargeable-Powerpoint/dp/B081SVDQ2S/

**Comment by nuke-web3** [comment]
@FlorianFranzen you wanted to try this out? please let us know what works? (generic linux, and if you can mac & windows, but there is a windows app AFAIK)

**Comment by FlorianFranzen** [comment]
I proposed a solution on #2.
